# Generated by Django 4.2.5 on 2023-09-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course_bought',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='lesson_bought',
            new_name='lesson',
        ),
    ]
