# Generated by Django 4.2.5 on 2023-09-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_course_bought_payment_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-payment_date',), 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
