# Generated by Django 4.2.5 on 2023-09-29 12:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0006_lesson_price'),
        ('payments', '0004_remove_payment_payment_type_payment_payment_method'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'course'), ('user', 'lesson')},
        ),
    ]
